AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS CloudFormation Template Create EC2InstanceWithSecurityGroup.'
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Default: t2.micro
    Description: instance type
    Type: String
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  AMIImageID:
    Description: AMI for EC2 Instance
    Type: String
    Default: ami-0b0af3577fe5e3532
    ConstraintDescription: must be a valid AMI.
  SubnetId:
    Description: existing SubnetID
    Type: String
    Default: subnet-01afa0de28f96dfd8
    ConstraintDescription: must be a valid Subnet.
  VPCID:
    Description: existing VPCID
    Type: String
    Default: vpc-0192907726f7d06d5
    ConstraintDescription: must be a valid VPC.


    
Resources: 
  RACAPACHESERVER: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !Ref AMIImageID
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref SubnetId
          GroupSet: 
            - !Ref SSHSecurityGroup
      KeyName: !Ref KeyName
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl enable httpd
          sudo service httpd start  
          sudo echo '<!DOCTYPE html> <html> <body style="background-color:rgb(250, 210, 210);"> <h1>vRA CLOUDFORMATION RAC DEPLOYMENT</h1> <p>Terraform Demo</p> <p>Application Version: V1</p> </body></html>' | sudo tee /var/www/html/index.html
          


      Tags:
        - Key: "Name"
          Value: "RAC_APACHE"
        - Key: "app"
          Value: "RAC"
        - Key: "business_unit"
          Value: "RTO"

  
  RACSQLSERVER: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !Ref AMIImageID
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref SubnetId
          GroupSet: 
            - !Ref SSHSecurityGroup
      KeyName: !Ref KeyName
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo yum install -y mysql-server
          sudo systemctl enable mysqld
          sudo systemctl start mysqld


      Tags:
        - Key: "Name"
          Value: "RAC_MYSQL"
        - Key: "app"
          Value: "RAC"
        - Key: "business_unit"
          Value: "RTO"


  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
           
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: !Ref SSHLocation

      SecurityGroupEgress: 
        - IpProtocol: "-1"
          FromPort: '0'
          ToPort: '0'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "RAC_SG_CF_TEMPLETE"
        - Key: "app"
          Value: "RAC"
        - Key: "business_unit"
          Value: "RTO"

      
Outputs:
  ApacheInstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref RACAPACHESERVER
  ApacheAZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt RACAPACHESERVER.AvailabilityZone
  ApacheAZPublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt RACAPACHESERVER.PublicDnsName
  ApachePublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt RACAPACHESERVER.PublicIp
  
  SqlInstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref RACSQLSERVER
  SqlAZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt RACSQLSERVER.AvailabilityZone
  SqlPublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt RACSQLSERVER.PublicDnsName
  SqlPublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt RACSQLSERVER.PublicIp
          
          
        
        
      
      
        

